### ISSUE TITLE
Command in the README

### ISSUE THREAD

**Issue by hiraksarkar** [kyzhu/assembltrie#2]
The command in the readme does not seem to have space between argument and option. Is that correct? 
>./astrie -c -L100 -K20 -h0 -s4 -iERR174310_1.fastq.gz -odest.out -e4 -n10
or 
>./astrie -c -L 100 -K 20 -h 0 -s 4 -i ERR174310_1.fastq.gz -o dest.out -e 4 -n 10

which one is correct or both?

**Comment by kyzhu** [comment]
Both works fine. Also, the input is not expected to be gzipped.

Thanks!
